name: Deploy to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Set environment
        id: env
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "prod_flag=--prod" >> $GITHUB_OUTPUT
          else
            echo "environment=preview" >> $GITHUB_OUTPUT
            echo "prod_flag=" >> $GITHUB_OUTPUT
          fi

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=${{ steps.env.outputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./client
        
      - name: Build Project
        run: vercel build ${{ steps.env.outputs.prod_flag }} --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./client
        
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt ${{ steps.env.outputs.prod_flag }} --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./client
